version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    container_name: redis-server

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --requirepass yourStrongPassword123
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "yourStrongPassword123", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data: