
students = [
    {
        "id": 1,
        "roll_no": "CSE2025001",
        "name": "Amit Ghosh",
        "age": 23,
        "gender": "Female",
        "course": "Mechanical",
        "semester": 5,
        "cgpa": 8.55,
        "attendance": 86,
        "email": "student1@college.com",
        "phone": "9831723604",
        "city": "Jaipur",
        "is_active": False,
        "subjects": {
            "Python": 91,
            "Java": 99,
            "DBMS": 98,
            "Operating Systems": 96,
            "Computer Networks": 88,
        },
    },
    {
        "id": 2,
        "roll_no": "CSE2025002",
        "name": "Ananya Ghosh",
        "age": 24,
        "gender": "Female",
        "course": "Information Technology",
        "semester": 1,
        "cgpa": 7.1,
        "attendance": 94,
        "email": "student2@college.com",
        "phone": "9875369759",
        "city": "Pune",
        "is_active": False,
        "subjects": {
            "Python": 99,
            "Java": 98,
            "DBMS": 95,
            "Operating Systems": 88,
            "Computer Networks": 87,
        },
    },
    {
        "id": 3,
        "roll_no": "CSE2025003",
        "name": "Rahul Das",
        "age": 18,
        "gender": "Female",
        "course": "Mechanical",
        "semester": 4,
        "cgpa": 7.41,
        "attendance": 95,
        "email": "student3@college.com",
        "phone": "9876120324",
        "city": "Hyderabad",
        "is_active": True,
        "subjects": {
            "Python": 65,
            "Java": 61,
            "DBMS": 77,
            "Operating Systems": 97,
            "Computer Networks": 68,
        },
    },
    {
        "id": 4,
        "roll_no": "CSE2025004",
        "name": "Vihaan Chatterjee",
        "age": 22,
        "gender": "Male",
        "course": "Civil",
        "semester": 6,
        "cgpa": 8.6,
        "attendance": 74,
        "email": "student4@college.com",
        "phone": "9814387816",
        "city": "Delhi",
        "is_active": True,
        "subjects": {
            "Python": 80,
            "Java": 60,
            "DBMS": 90,
            "Operating Systems": 77,
            "Computer Networks": 72,
        },
    },
    {
        "id": 5,
        "roll_no": "CSE2025005",
        "name": "Rahul Gupta",
        "age": 22,
        "gender": "Male",
        "course": "Computer Science",
        "semester": 4,
        "cgpa": 9.83,
        "attendance": 76,
        "email": "student5@college.com",
        "phone": "9876568579",
        "city": "Hyderabad",
        "is_active": True,
        "subjects": {
            "Python": 63,
            "Java": 98,
            "DBMS": 62,
            "Operating Systems": 79,
            "Computer Networks": 90,
        },
    },
    {
        "id": 6,
        "roll_no": "CSE2025006",
        "name": "Ananya Sharma",
        "age": 24,
        "gender": "Male",
        "course": "Information Technology",
        "semester": 6,
        "cgpa": 7.04,
        "attendance": 98,
        "email": "student6@college.com",
        "phone": "9898713607",
        "city": "Jaipur",
        "is_active": False,
        "subjects": {
            "Python": 91,
            "Java": 92,
            "DBMS": 63,
            "Operating Systems": 94,
            "Computer Networks": 63,
        },
    },
    {
        "id": 7,
        "roll_no": "CSE2025007",
        "name": "Rahul Banerjee",
        "age": 18,
        "gender": "Male",
        "course": "Electrical",
        "semester": 7,
        "cgpa": 9.78,
        "attendance": 92,
        "email": "student7@college.com",
        "phone": "9899869686",
        "city": "Mumbai",
        "is_active": True,
        "subjects": {
            "Python": 62,
            "Java": 62,
            "DBMS": 93,
            "Operating Systems": 92,
            "Computer Networks": 82,
        },
    },
    {
        "id": 8,
        "roll_no": "CSE2025008",
        "name": "Ananya Mukherjee",
        "age": 21,
        "gender": "Male",
        "course": "Electrical",
        "semester": 7,
        "cgpa": 9.64,
        "attendance": 90,
        "email": "student8@college.com",
        "phone": "9874851983",
        "city": "Delhi",
        "is_active": True,
        "subjects": {
            "Python": 63,
            "Java": 88,
            "DBMS": 98,
            "Operating Systems": 93,
            "Computer Networks": 87,
        },
    },
    {
        "id": 9,
        "roll_no": "CSE2025009",
        "name": "Krishna Banerjee",
        "age": 18,
        "gender": "Male",
        "course": "Mechanical",
        "semester": 1,
        "cgpa": 7.84,
        "attendance": 90,
        "email": "student9@college.com",
        "phone": "9898581006",
        "city": "Bangalore",
        "is_active": True,
        "subjects": {
            "Python": 85,
            "Java": 70,
            "DBMS": 81,
            "Operating Systems": 80,
            "Computer Networks": 86,
        },
    },
    {
        "id": 10,
        "roll_no": "CSE2025010",
        "name": "Krishna Santra",
        "age": 20,
        "gender": "Male",
        "course": "Computer Science",
        "semester": 1,
        "cgpa": 9.18,
        "attendance": 84,
        "email": "student10@college.com",
        "phone": "9899697010",
        "city": "Pune",
        "is_active": False,
        "subjects": {
            "Python": 60,
            "Java": 82,
            "DBMS": 64,
            "Operating Systems": 73,
            "Computer Networks": 69,
        },
    },
    {
        "id": 11,
        "roll_no": "CSE2025011",
        "name": "Aisha Sharma",
        "age": 19,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 4,
        "cgpa": 9.48,
        "attendance": 93,
        "email": "student11@college.com",
        "phone": "9827920040",
        "city": "Chennai",
        "is_active": False,
        "subjects": {
            "Python": 75,
            "Java": 95,
            "DBMS": 90,
            "Operating Systems": 65,
            "Computer Networks": 80,
        },
    },
    {
        "id": 12,
        "roll_no": "CSE2025012",
        "name": "Rohan Yadav",
        "age": 24,
        "gender": "Male",
        "course": "Electrical",
        "semester": 4,
        "cgpa": 7.73,
        "attendance": 75,
        "email": "student12@college.com",
        "phone": "9825685434",
        "city": "Pune",
        "is_active": False,
        "subjects": {
            "Python": 85,
            "Java": 87,
            "DBMS": 82,
            "Operating Systems": 67,
            "Computer Networks": 70,
        },
    },
    {
        "id": 13,
        "roll_no": "CSE2025013",
        "name": "Amit Yadav",
        "age": 20,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 8,
        "cgpa": 9.46,
        "attendance": 92,
        "email": "student13@college.com",
        "phone": "9826352501",
        "city": "Delhi",
        "is_active": True,
        "subjects": {
            "Python": 96,
            "Java": 80,
            "DBMS": 67,
            "Operating Systems": 98,
            "Computer Networks": 85,
        },
    },
    {
        "id": 14,
        "roll_no": "CSE2025014",
        "name": "Krishna Patel",
        "age": 22,
        "gender": "Female",
        "course": "Information Technology",
        "semester": 1,
        "cgpa": 8.63,
        "attendance": 90,
        "email": "student14@college.com",
        "phone": "9824742078",
        "city": "Mumbai",
        "is_active": False,
        "subjects": {
            "Python": 68,
            "Java": 88,
            "DBMS": 92,
            "Operating Systems": 95,
            "Computer Networks": 81,
        },
    },
    {
        "id": 15,
        "roll_no": "CSE2025015",
        "name": "Rohan Singh",
        "age": 23,
        "gender": "Female",
        "course": "Civil",
        "semester": 4,
        "cgpa": 8.28,
        "attendance": 85,
        "email": "student15@college.com",
        "phone": "9833593926",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 79,
            "Java": 90,
            "DBMS": 62,
            "Operating Systems": 71,
            "Computer Networks": 87,
        },
    },
    {
        "id": 16,
        "roll_no": "CSE2025016",
        "name": "Priya Mukherjee",
        "age": 24,
        "gender": "Male",
        "course": "Electrical",
        "semester": 4,
        "cgpa": 9.41,
        "attendance": 82,
        "email": "student16@college.com",
        "phone": "9830094323",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 75,
            "Java": 86,
            "DBMS": 96,
            "Operating Systems": 72,
            "Computer Networks": 90,
        },
    },
    {
        "id": 17,
        "roll_no": "CSE2025017",
        "name": "Pooja Chatterjee",
        "age": 18,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 3,
        "cgpa": 9.69,
        "attendance": 75,
        "email": "student17@college.com",
        "phone": "9891149024",
        "city": "Delhi",
        "is_active": True,
        "subjects": {
            "Python": 74,
            "Java": 97,
            "DBMS": 78,
            "Operating Systems": 87,
            "Computer Networks": 84,
        },
    },
    {
        "id": 18,
        "roll_no": "CSE2025018",
        "name": "Krishna Das",
        "age": 20,
        "gender": "Female",
        "course": "Mechanical",
        "semester": 2,
        "cgpa": 6.51,
        "attendance": 90,
        "email": "student18@college.com",
        "phone": "9851351473",
        "city": "Chennai",
        "is_active": True,
        "subjects": {
            "Python": 94,
            "Java": 99,
            "DBMS": 94,
            "Operating Systems": 89,
            "Computer Networks": 87,
        },
    },
    {
        "id": 19,
        "roll_no": "CSE2025019",
        "name": "Kavya Yadav",
        "age": 19,
        "gender": "Male",
        "course": "Electrical",
        "semester": 7,
        "cgpa": 8.54,
        "attendance": 79,
        "email": "student19@college.com",
        "phone": "9833402495",
        "city": "Mumbai",
        "is_active": True,
        "subjects": {
            "Python": 72,
            "Java": 75,
            "DBMS": 78,
            "Operating Systems": 92,
            "Computer Networks": 86,
        },
    },
    {
        "id": 20,
        "roll_no": "CSE2025020",
        "name": "Priya Singh",
        "age": 23,
        "gender": "Male",
        "course": "Civil",
        "semester": 8,
        "cgpa": 9.72,
        "attendance": 82,
        "email": "student20@college.com",
        "phone": "9848263777",
        "city": "Pune",
        "is_active": True,
        "subjects": {
            "Python": 83,
            "Java": 91,
            "DBMS": 69,
            "Operating Systems": 76,
            "Computer Networks": 74,
        },
    },
    {
        "id": 21,
        "roll_no": "CSE2025021",
        "name": "Krishna Ghosh",
        "age": 24,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 5,
        "cgpa": 9.54,
        "attendance": 83,
        "email": "student21@college.com",
        "phone": "9812537067",
        "city": "Hyderabad",
        "is_active": True,
        "subjects": {
            "Python": 64,
            "Java": 61,
            "DBMS": 61,
            "Operating Systems": 72,
            "Computer Networks": 72,
        },
    },
    {
        "id": 22,
        "roll_no": "CSE2025022",
        "name": "Arjun Singh",
        "age": 23,
        "gender": "Male",
        "course": "Computer Science",
        "semester": 2,
        "cgpa": 6.73,
        "attendance": 72,
        "email": "student22@college.com",
        "phone": "9858463453",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 61,
            "Java": 77,
            "DBMS": 63,
            "Operating Systems": 90,
            "Computer Networks": 94,
        },
    },
    {
        "id": 23,
        "roll_no": "CSE2025023",
        "name": "Vivaan Singh",
        "age": 20,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 8,
        "cgpa": 9.81,
        "attendance": 74,
        "email": "student23@college.com",
        "phone": "9831144834",
        "city": "Kolkata",
        "is_active": True,
        "subjects": {
            "Python": 84,
            "Java": 95,
            "DBMS": 100,
            "Operating Systems": 89,
            "Computer Networks": 76,
        },
    },
    {
        "id": 24,
        "roll_no": "CSE2025024",
        "name": "Pooja Mukherjee",
        "age": 19,
        "gender": "Male",
        "course": "Information Technology",
        "semester": 7,
        "cgpa": 8.48,
        "attendance": 76,
        "email": "student24@college.com",
        "phone": "9864556551",
        "city": "Bangalore",
        "is_active": False,
        "subjects": {
            "Python": 83,
            "Java": 79,
            "DBMS": 76,
            "Operating Systems": 87,
            "Computer Networks": 94,
        },
    },
    {
        "id": 25,
        "roll_no": "CSE2025025",
        "name": "Aditya Sharma",
        "age": 21,
        "gender": "Male",
        "course": "Electronics",
        "semester": 5,
        "cgpa": 7.64,
        "attendance": 79,
        "email": "student25@college.com",
        "phone": "9830205848",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 81,
            "Java": 68,
            "DBMS": 78,
            "Operating Systems": 88,
            "Computer Networks": 83,
        },
    },
    {
        "id": 26,
        "roll_no": "CSE2025026",
        "name": "Sneha Verma",
        "age": 23,
        "gender": "Male",
        "course": "Computer Science",
        "semester": 4,
        "cgpa": 9.36,
        "attendance": 81,
        "email": "student26@college.com",
        "phone": "9858949043",
        "city": "Chennai",
        "is_active": True,
        "subjects": {
            "Python": 83,
            "Java": 60,
            "DBMS": 84,
            "Operating Systems": 99,
            "Computer Networks": 89,
        },
    },
    {
        "id": 27,
        "roll_no": "CSE2025027",
        "name": "Ishita Mishra",
        "age": 24,
        "gender": "Male",
        "course": "Information Technology",
        "semester": 8,
        "cgpa": 7.87,
        "attendance": 95,
        "email": "student27@college.com",
        "phone": "9871760119",
        "city": "Mumbai",
        "is_active": False,
        "subjects": {
            "Python": 93,
            "Java": 62,
            "DBMS": 84,
            "Operating Systems": 66,
            "Computer Networks": 72,
        },
    },
    {
        "id": 28,
        "roll_no": "CSE2025028",
        "name": "Vivaan Das",
        "age": 22,
        "gender": "Female",
        "course": "Mechanical",
        "semester": 8,
        "cgpa": 7.51,
        "attendance": 80,
        "email": "student28@college.com",
        "phone": "9899741836",
        "city": "Pune",
        "is_active": True,
        "subjects": {
            "Python": 67,
            "Java": 63,
            "DBMS": 65,
            "Operating Systems": 79,
            "Computer Networks": 97,
        },
    },
    {
        "id": 29,
        "roll_no": "CSE2025029",
        "name": "Sneha Singh",
        "age": 22,
        "gender": "Female",
        "course": "Civil",
        "semester": 3,
        "cgpa": 7.87,
        "attendance": 98,
        "email": "student29@college.com",
        "phone": "9821099522",
        "city": "Hyderabad",
        "is_active": True,
        "subjects": {
            "Python": 87,
            "Java": 68,
            "DBMS": 82,
            "Operating Systems": 64,
            "Computer Networks": 88,
        },
    },
    {
        "id": 30,
        "roll_no": "CSE2025030",
        "name": "Aisha Banerjee",
        "age": 23,
        "gender": "Male",
        "course": "Information Technology",
        "semester": 4,
        "cgpa": 7.41,
        "attendance": 92,
        "email": "student30@college.com",
        "phone": "9883013525",
        "city": "Chennai",
        "is_active": True,
        "subjects": {
            "Python": 93,
            "Java": 93,
            "DBMS": 91,
            "Operating Systems": 76,
            "Computer Networks": 96,
        },
    },
    {
        "id": 31,
        "roll_no": "CSE2025031",
        "name": "Aarav Singh",
        "age": 20,
        "gender": "Female",
        "course": "Electrical",
        "semester": 1,
        "cgpa": 8.27,
        "attendance": 99,
        "email": "student31@college.com",
        "phone": "9875687526",
        "city": "Bangalore",
        "is_active": True,
        "subjects": {
            "Python": 76,
            "Java": 81,
            "DBMS": 62,
            "Operating Systems": 94,
            "Computer Networks": 99,
        },
    },
    {
        "id": 32,
        "roll_no": "CSE2025032",
        "name": "Vivaan Mukherjee",
        "age": 23,
        "gender": "Female",
        "course": "Information Technology",
        "semester": 2,
        "cgpa": 7.86,
        "attendance": 89,
        "email": "student32@college.com",
        "phone": "9831098757",
        "city": "Pune",
        "is_active": False,
        "subjects": {
            "Python": 96,
            "Java": 94,
            "DBMS": 87,
            "Operating Systems": 90,
            "Computer Networks": 64,
        },
    },
    {
        "id": 33,
        "roll_no": "CSE2025033",
        "name": "Riya Chatterjee",
        "age": 24,
        "gender": "Male",
        "course": "Information Technology",
        "semester": 7,
        "cgpa": 6.51,
        "attendance": 90,
        "email": "student33@college.com",
        "phone": "9830217171",
        "city": "Hyderabad",
        "is_active": False,
        "subjects": {
            "Python": 82,
            "Java": 83,
            "DBMS": 91,
            "Operating Systems": 75,
            "Computer Networks": 67,
        },
    },
    {
        "id": 34,
        "roll_no": "CSE2025034",
        "name": "Ananya Ghosh",
        "age": 18,
        "gender": "Male",
        "course": "Civil",
        "semester": 4,
        "cgpa": 9.65,
        "attendance": 84,
        "email": "student34@college.com",
        "phone": "9899427835",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 62,
            "Java": 72,
            "DBMS": 73,
            "Operating Systems": 69,
            "Computer Networks": 88,
        },
    },
    {
        "id": 35,
        "roll_no": "CSE2025035",
        "name": "Riya Mukherjee",
        "age": 19,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 7,
        "cgpa": 6.81,
        "attendance": 100,
        "email": "student35@college.com",
        "phone": "9865818390",
        "city": "Pune",
        "is_active": True,
        "subjects": {
            "Python": 79,
            "Java": 75,
            "DBMS": 93,
            "Operating Systems": 90,
            "Computer Networks": 98,
        },
    },
    {
        "id": 36,
        "roll_no": "CSE2025036",
        "name": "Ishita Chatterjee",
        "age": 20,
        "gender": "Female",
        "course": "Civil",
        "semester": 1,
        "cgpa": 8.86,
        "attendance": 86,
        "email": "student36@college.com",
        "phone": "9814599715",
        "city": "Chennai",
        "is_active": False,
        "subjects": {
            "Python": 83,
            "Java": 98,
            "DBMS": 78,
            "Operating Systems": 64,
            "Computer Networks": 66,
        },
    },
    {
        "id": 37,
        "roll_no": "CSE2025037",
        "name": "Rahul Chatterjee",
        "age": 23,
        "gender": "Male",
        "course": "Electronics",
        "semester": 7,
        "cgpa": 9.2,
        "attendance": 70,
        "email": "student37@college.com",
        "phone": "9877132349",
        "city": "Hyderabad",
        "is_active": True,
        "subjects": {
            "Python": 68,
            "Java": 77,
            "DBMS": 65,
            "Operating Systems": 84,
            "Computer Networks": 99,
        },
    },
    {
        "id": 38,
        "roll_no": "CSE2025038",
        "name": "Vihaan Chatterjee",
        "age": 24,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 3,
        "cgpa": 8.11,
        "attendance": 100,
        "email": "student38@college.com",
        "phone": "9812759971",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 68,
            "Java": 77,
            "DBMS": 66,
            "Operating Systems": 79,
            "Computer Networks": 89,
        },
    },
    {
        "id": 39,
        "roll_no": "CSE2025039",
        "name": "Aditya Singh",
        "age": 22,
        "gender": "Male",
        "course": "Information Technology",
        "semester": 5,
        "cgpa": 9.4,
        "attendance": 79,
        "email": "student39@college.com",
        "phone": "9866448992",
        "city": "Delhi",
        "is_active": False,
        "subjects": {
            "Python": 60,
            "Java": 69,
            "DBMS": 80,
            "Operating Systems": 69,
            "Computer Networks": 71,
        },
    },
    {
        "id": 40,
        "roll_no": "CSE2025040",
        "name": "Priya Ghosh",
        "age": 23,
        "gender": "Male",
        "course": "Electrical",
        "semester": 4,
        "cgpa": 9.22,
        "attendance": 91,
        "email": "student40@college.com",
        "phone": "9869487327",
        "city": "Chennai",
        "is_active": False,
        "subjects": {
            "Python": 93,
            "Java": 73,
            "DBMS": 78,
            "Operating Systems": 88,
            "Computer Networks": 82,
        },
    },
    {
        "id": 41,
        "roll_no": "CSE2025041",
        "name": "Krishna Mukherjee",
        "age": 20,
        "gender": "Female",
        "course": "Mechanical",
        "semester": 5,
        "cgpa": 7.23,
        "attendance": 98,
        "email": "student41@college.com",
        "phone": "9835827041",
        "city": "Jaipur",
        "is_active": True,
        "subjects": {
            "Python": 80,
            "Java": 94,
            "DBMS": 60,
            "Operating Systems": 64,
            "Computer Networks": 92,
        },
    },
    {
        "id": 42,
        "roll_no": "CSE2025042",
        "name": "Aisha Gupta",
        "age": 19,
        "gender": "Female",
        "course": "Electrical",
        "semester": 7,
        "cgpa": 9.25,
        "attendance": 75,
        "email": "student42@college.com",
        "phone": "9898258958",
        "city": "Pune",
        "is_active": True,
        "subjects": {
            "Python": 67,
            "Java": 79,
            "DBMS": 76,
            "Operating Systems": 83,
            "Computer Networks": 75,
        },
    },
    {
        "id": 43,
        "roll_no": "CSE2025043",
        "name": "Rohan Santra",
        "age": 21,
        "gender": "Male",
        "course": "Electronics",
        "semester": 5,
        "cgpa": 7.2,
        "attendance": 75,
        "email": "student43@college.com",
        "phone": "9810065569",
        "city": "Delhi",
        "is_active": True,
        "subjects": {
            "Python": 61,
            "Java": 62,
            "DBMS": 62,
            "Operating Systems": 86,
            "Computer Networks": 86,
        },
    },
    {
        "id": 44,
        "roll_no": "CSE2025044",
        "name": "Meera Singh",
        "age": 21,
        "gender": "Male",
        "course": "Computer Science",
        "semester": 5,
        "cgpa": 9.41,
        "attendance": 78,
        "email": "student44@college.com",
        "phone": "9894958049",
        "city": "Chennai",
        "is_active": False,
        "subjects": {
            "Python": 94,
            "Java": 92,
            "DBMS": 84,
            "Operating Systems": 75,
            "Computer Networks": 82,
        },
    },
    {
        "id": 45,
        "roll_no": "CSE2025045",
        "name": "Amit Banerjee",
        "age": 19,
        "gender": "Female",
        "course": "Civil",
        "semester": 2,
        "cgpa": 8.96,
        "attendance": 89,
        "email": "student45@college.com",
        "phone": "9814774659",
        "city": "Mumbai",
        "is_active": False,
        "subjects": {
            "Python": 79,
            "Java": 78,
            "DBMS": 92,
            "Operating Systems": 100,
            "Computer Networks": 77,
        },
    },
    {
        "id": 46,
        "roll_no": "CSE2025046",
        "name": "Riya Yadav",
        "age": 24,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 3,
        "cgpa": 7.98,
        "attendance": 95,
        "email": "student46@college.com",
        "phone": "9848625150",
        "city": "Delhi",
        "is_active": True,
        "subjects": {
            "Python": 63,
            "Java": 85,
            "DBMS": 85,
            "Operating Systems": 95,
            "Computer Networks": 86,
        },
    },
    {
        "id": 47,
        "roll_no": "CSE2025047",
        "name": "Riya Verma",
        "age": 23,
        "gender": "Male",
        "course": "Electrical",
        "semester": 6,
        "cgpa": 8.33,
        "attendance": 97,
        "email": "student47@college.com",
        "phone": "9813533067",
        "city": "Chennai",
        "is_active": True,
        "subjects": {
            "Python": 95,
            "Java": 87,
            "DBMS": 67,
            "Operating Systems": 86,
            "Computer Networks": 95,
        },
    },
    {
        "id": 48,
        "roll_no": "CSE2025048",
        "name": "Aarav Patel",
        "age": 23,
        "gender": "Female",
        "course": "Civil",
        "semester": 8,
        "cgpa": 6.67,
        "attendance": 87,
        "email": "student48@college.com",
        "phone": "9817899065",
        "city": "Jaipur",
        "is_active": False,
        "subjects": {
            "Python": 99,
            "Java": 90,
            "DBMS": 71,
            "Operating Systems": 75,
            "Computer Networks": 63,
        },
    },
    {
        "id": 49,
        "roll_no": "CSE2025049",
        "name": "Aditya Singh",
        "age": 22,
        "gender": "Female",
        "course": "Computer Science",
        "semester": 5,
        "cgpa": 6.83,
        "attendance": 85,
        "email": "student49@college.com",
        "phone": "9863885951",
        "city": "Bangalore",
        "is_active": True,
        "subjects": {
            "Python": 81,
            "Java": 68,
            "DBMS": 79,
            "Operating Systems": 82,
            "Computer Networks": 94,
        },
    },
    {
        "id": 50,
        "roll_no": "CSE2025050",
        "name": "Sneha Kumar",
        "age": 24,
        "gender": "Female",
        "course": "Mechanical",
        "semester": 1,
        "cgpa": 9.21,
        "attendance": 88,
        "email": "student50@college.com",
        "phone": "9848570133",
        "city": "Kolkata",
        "is_active": True,
        "subjects": {
            "Python": 93,
            "Java": 92,
            "DBMS": 99,
            "Operating Systems": 98,
            "Computer Networks": 98,
        },
    },
]
